language: python
python: 2.7
install:
  - pip install tox
script:
  - tox -e $TOXENV
env:
  - TOXENV=py34-dj1.7
  - TOXENV=py33-dj1.7
  - TOXENV=py27-dj1.7
  - TOXENV=py33-dj1.6
  - TOXENV=py27-dj1.6
